#ifndef STM32PP_EXTI_H
#define STM32PP_EXTI_H

#include "common.hpp"
#include <libopencm3/stm32/exti.h>
#include <libopencm3/cm3/nvic.h>

#define STM32PP_DEFINE_EXTI_PERIPH_INFO(id, irq)        \
    STM32PP_PERIPH_INFO(id)                             \
    static constexpr uint8_t kIrqn = irq;              \
}

STM32PP_DEFINE_EXTI_PERIPH_INFO(EXTI0, NVIC_EXTI0_IRQ);
STM32PP_DEFINE_EXTI_PERIPH_INFO(EXTI1, NVIC_EXTI1_IRQ);
STM32PP_DEFINE_EXTI_PERIPH_INFO(EXTI2, NVIC_EXTI2_IRQ);
STM32PP_DEFINE_EXTI_PERIPH_INFO(EXTI3, NVIC_EXTI3_IRQ);
STM32PP_DEFINE_EXTI_PERIPH_INFO(EXTI4, NVIC_EXTI4_IRQ);

STM32PP_DEFINE_EXTI_PERIPH_INFO(EXTI5, NVIC_EXTI9_5_IRQ);
STM32PP_DEFINE_EXTI_PERIPH_INFO(EXTI6, NVIC_EXTI9_5_IRQ);
STM32PP_DEFINE_EXTI_PERIPH_INFO(EXTI7, NVIC_EXTI9_5_IRQ);
STM32PP_DEFINE_EXTI_PERIPH_INFO(EXTI8, NVIC_EXTI9_5_IRQ);
STM32PP_DEFINE_EXTI_PERIPH_INFO(EXTI9, NVIC_EXTI9_5_IRQ);

STM32PP_DEFINE_EXTI_PERIPH_INFO(EXTI10, NVIC_EXTI15_10_IRQ);
STM32PP_DEFINE_EXTI_PERIPH_INFO(EXTI11, NVIC_EXTI15_10_IRQ);
STM32PP_DEFINE_EXTI_PERIPH_INFO(EXTI12, NVIC_EXTI15_10_IRQ);
STM32PP_DEFINE_EXTI_PERIPH_INFO(EXTI13, NVIC_EXTI15_10_IRQ);
STM32PP_DEFINE_EXTI_PERIPH_INFO(EXTI14, NVIC_EXTI15_10_IRQ);
STM32PP_DEFINE_EXTI_PERIPH_INFO(EXTI15, NVIC_EXTI15_10_IRQ);

#endif
